In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("credit_data.csv")
data

,id,customer_id,name,age,income,debt,credit_score,num_accounts,employment_type,risk_grade,region,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default
0,1,CUST0001,Customer_001,25,52466.0,13887.0,775,5,Salaried,A,South,214544.0,30744.0,73659.0,15290.0,32354.0,2107.0,0
1,2,CUST0002,Customer_002,57,74188.0,500.0,598,2,Self-Employed,A,East,130761.0,19542.0,88734.0,12895.0,19499.0,100.0,0
2,3,CUST0003,Customer_003,51,57827.0,30807.0,531,10,Self-Employed,A,North,234444.0,53255.0,48647.0,3954.0,8629.0,5154.0,0
3,4,CUST0004,Customer_004,41,52145.0,14022.0,688,9,Salaried,B,West,233162.0,17957.0,46928.0,8187.0,17720.0,738.0,0
4,5,CUST0005,Customer_005,41,36358.0,31375.0,754,9,Self-Employed,D,West,114660.0,41472.0,52901.0,4611.0,6191.0,4798.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,CUST0296,Customer_296,45,61515.0,500.0,759,4,Salaried,A,East,184659.0,21152.0,77380.0,5499.0,6792.0,100.0,0
296,297,CUST0297,Customer_297,60,78772.0,30021.0,635,1,Unemployed,C,East,310686.0,42533.0,95663.0,6416.0,14057.0,3497.0,1
297,38,CUST0038,Customer_038,59,62718.0,35199.0,685,7,Salaried,C,North,192065.0,44816.0,92032.0,21804.0,34626.0,5677.0,1
298,129,CUST0129,Customer_129,48,61945.0,21144.0,676,5,Salaried,A,North,216921.0,37052.0,103804.0,24199.0,44247.0,3043.0,0
299,242,CUST0242,Customer_242,48,59973.0,12251.0,698,10,Salaried,D,North,213307.0,26039.0,62658.0,21167.0,39116.0,1089.0,1

In [4]:
df=pd.DataFrame(data)
df

,id,customer_id,name,age,income,debt,credit_score,num_accounts,employment_type,risk_grade,region,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default
0,1,CUST0001,Customer_001,25,52466.0,13887.0,775,5,Salaried,A,South,214544.0,30744.0,73659.0,15290.0,32354.0,2107.0,0
1,2,CUST0002,Customer_002,57,74188.0,500.0,598,2,Self-Employed,A,East,130761.0,19542.0,88734.0,12895.0,19499.0,100.0,0
2,3,CUST0003,Customer_003,51,57827.0,30807.0,531,10,Self-Employed,A,North,234444.0,53255.0,48647.0,3954.0,8629.0,5154.0,0
3,4,CUST0004,Customer_004,41,52145.0,14022.0,688,9,Salaried,B,West,233162.0,17957.0,46928.0,8187.0,17720.0,738.0,0
4,5,CUST0005,Customer_005,41,36358.0,31375.0,754,9,Self-Employed,D,West,114660.0,41472.0,52901.0,4611.0,6191.0,4798.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,CUST0296,Customer_296,45,61515.0,500.0,759,4,Salaried,A,East,184659.0,21152.0,77380.0,5499.0,6792.0,100.0,0
296,297,CUST0297,Customer_297,60,78772.0,30021.0,635,1,Unemployed,C,East,310686.0,42533.0,95663.0,6416.0,14057.0,3497.0,1
297,38,CUST0038,Customer_038,59,62718.0,35199.0,685,7,Salaried,C,North,192065.0,44816.0,92032.0,21804.0,34626.0,5677.0,1
298,129,CUST0129,Customer_129,48,61945.0,21144.0,676,5,Salaried,A,North,216921.0,37052.0,103804.0,24199.0,44247.0,3043.0,0
299,242,CUST0242,Customer_242,48,59973.0,12251.0,698,10,Salaried,D,North,213307.0,26039.0,62658.0,21167.0,39116.0,1089.0,1

In [5]:
df.head()
df.tail(105)
print(df.shape)
print(df.columns.tolist())

(300, 18)
['id', 'customer_id', 'name', 'age', 'income', 'debt', 'credit_score', 'num_accounts', 'employment_type', 'risk_grade', 'region', 'credit_limit', 'used_credit', 'revenue', 'profit', 'ebitda', 'interest_expense', 'default']

In [6]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                300 non-null    int64
 1   customer_id       300 non-null    str
 2   name              300 non-null    str
 3   age               300 non-null    int64
 4   income            285 non-null    float64
 5   debt              291 non-null    float64
 6   credit_score      300 non-null    int64
 7   num_accounts      300 non-null    int64
 8   employment_type   300 non-null    str
 9   risk_grade        300 non-null    str
 10  region            300 non-null    str
 11  credit_limit      300 non-null    float64
 12  used_credit       300 non-null    float64
 13  revenue           300 non-null    float64
 14  profit            300 non-null    float64
 15  ebitda            300 non-null    float64
 16  interest_expense  300 non-null    float64
 17  default           300 non-null    int64
dtypes: float64(8), int64(5), str(5)
memory usage: 42.3 KB

,id,age,income,debt,credit_score,num_accounts,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default
count,300.000000,300.000000,285.000000,291.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,148.873333,44.163333,54906.764912,17582.206186,680.313333,5.333333,176448.816667,27689.506667,72850.530000,14230.933333,23647.270000,2082.200000,0.243333
std,85.865906,12.749581,17719.744926,11252.656350,77.729540,2.861734,84437.552911,13638.581479,30076.572028,9020.472150,15325.382011,1578.922729,0.429812
min,1.000000,21.000000,12000.000000,500.000000,388.000000,1.000000,21255.000000,500.000000,16085.000000,1709.000000,3108.000000,100.000000,0.000000
25%,74.750000,34.000000,42473.000000,8586.000000,635.000000,3.000000,115230.750000,16804.500000,51409.000000,7243.500000,12141.500000,950.250000,0.000000
50%,148.500000,44.000000,55590.000000,16967.000000,683.000000,5.000000,162548.500000,27823.500000,67140.000000,12625.000000,19855.500000,1902.500000,0.000000
75%,223.250000,55.000000,65488.000000,25001.000000,729.000000,8.000000,219598.750000,37470.750000,91750.250000,19305.750000,31728.750000,2854.500000,0.000000
max,297.000000,67.000000,107291.000000,49172.000000,850.000000,10.000000,500000.000000,64785.000000,172290.000000,57716.000000,85700.000000,8097.000000,1.000000

In [7]:
df[df["age"]>44]

,id,customer_id,name,age,income,debt,credit_score,num_accounts,employment_type,risk_grade,region,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default
1,2,CUST0002,Customer_002,57,74188.0,500.0,598,2,Self-Employed,A,East,130761.0,19542.0,88734.0,12895.0,19499.0,100.0,0
2,3,CUST0003,Customer_003,51,57827.0,30807.0,531,10,Self-Employed,A,North,234444.0,53255.0,48647.0,3954.0,8629.0,5154.0,0
5,6,CUST0006,Customer_006,61,24856.0,22601.0,824,4,Salaried,C,South,81637.0,32680.0,44630.0,7727.0,14797.0,2456.0,0
7,8,CUST0008,Customer_008,53,54032.0,22185.0,650,9,Unemployed,A,South,264384.0,27640.0,73353.0,24149.0,45657.0,1129.0,0
10,11,CUST0011,Customer_011,45,72689.0,18833.0,656,5,Salaried,A,East,153507.0,23455.0,97782.0,18317.0,23384.0,2883.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,CUST0296,Customer_296,45,61515.0,500.0,759,4,Salaried,A,East,184659.0,21152.0,77380.0,5499.0,6792.0,100.0,0
296,297,CUST0297,Customer_297,60,78772.0,30021.0,635,1,Unemployed,C,East,310686.0,42533.0,95663.0,6416.0,14057.0,3497.0,1
297,38,CUST0038,Customer_038,59,62718.0,35199.0,685,7,Salaried,C,North,192065.0,44816.0,92032.0,21804.0,34626.0,5677.0,1
298,129,CUST0129,Customer_129,48,61945.0,21144.0,676,5,Salaried,A,North,216921.0,37052.0,103804.0,24199.0,44247.0,3043.0,0
299,242,CUST0242,Customer_242,48,59973.0,12251.0,698,10,Salaried,D,North,213307.0,26039.0,62658.0,21167.0,39116.0,1089.0,1

In [8]:
df[["id","num_accounts","default"]]

      id  num_accounts  default
0      1             5        0
1      2             2        0
2      3            10        0
3      4             9        0
4      5             9        1
..   ...           ...      ...
295  296             4        0
296  297             1        1
297   38             7        1
298  129             5        0
299  242            10        1

[300 rows x 3 columns]

In [9]:
df.loc[100:156]

,id,customer_id,name,age,income,debt,credit_score,num_accounts,employment_type,risk_grade,region,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default
100,101,CUST0101,Customer_101,60,88064.0,14959.0,683,9,Salaried,D,East,262677.0,26914.0,113744.0,38780.0,68459.0,2302.0,1
101,102,CUST0102,Customer_102,30,107291.0,16090.0,820,6,Salaried,A,West,500000.0,35671.0,172290.0,13823.0,17182.0,1847.0,0
102,103,CUST0103,Customer_103,58,33912.0,20441.0,673,2,Self-Employed,A,South,110500.0,30833.0,57486.0,13087.0,16742.0,3482.0,0
103,104,CUST0104,Customer_104,21,48372.0,5898.0,690,2,Salaried,B,West,236973.0,19371.0,42089.0,5351.0,10146.0,772.0,0
104,105,CUST0105,Customer_105,58,61148.0,26482.0,709,5,Self-Employed,C,South,147117.0,39046.0,84068.0,17897.0,22761.0,3095.0,1
105,106,CUST0106,Customer_106,57,86117.0,25952.0,850,6,Salaried,A,North,281250.0,33934.0,109134.0,15948.0,26746.0,3697.0,0
106,107,CUST0107,Customer_107,57,37237.0,22620.0,748,6,Salaried,B,South,167878.0,35455.0,52664.0,7112.0,10943.0,2613.0,0
107,108,CUST0108,Customer_108,52,50585.0,24678.0,623,3,Salaried,C,East,155239.0,50319.0,63093.0,14016.0,20016.0,4136.0,0
108,109,CUST0109,Customer_109,43,68992.0,21557.0,758,6,Salaried,B,East,170976.0,29664.0,82697.0,8683.0,12059.0,1595.0,0
109,110,CUST0110,Customer_110,54,62826.0,42421.0,651,3,Self-Employed,A,West,282350.0,55357.0,79907.0,15241.0,29924.0,7489.0,0
110,111,CUST0111,Customer_111,34,48229.0,16955.0,641,7,Salaried,A,North,138157.0,35759.0,66652.0,16346.0,35169.0,2638.0,0
111,112,CUST0112,Customer_112,57,52591.0,14315.0,753,8,Salaried,B,South,176576.0,32297.0,68420.0,6052.0,8111.0,2318.0,0
112,113,CUST0113,Customer_113,47,30252.0,8958.0,682,7,Unemployed,B,West,148775.0,19040.0,38485.0,12668.0,27359.0,1010.0,1
113,114,CUST0114,Customer_114,42,50713.0,5613.0,702,1,Unemployed,C,South,109169.0,500.0,82045.0,16550.0,29703.0,892.0,0
114,115,CUST0115,Customer_115,44,50205.0,3066.0,681,10,Self-Employed,B,North,128269.0,16683.0,77599.0,22958.0,42281.0,276.0,0
115,116,CUST0116,Customer_116,47,59179.0,7334.0,707,1,Salaried,C,West,95204.0,1798.0,67546.0,16628.0,31758.0,1093.0,0
116,117,CUST0117,Customer_117,22,45004.0,17152.0,714,10,Salaried,D,South,129226.0,37442.0,72032.0,18944.0,36072.0,1171.0,1
117,118,CUST0118,Customer_118,27,63488.0,22012.0,525,1,Self-Employed,B,West,139714.0,33198.0,104987.0,27805.0,56161.0,1979.0,0
118,119,CUST0119,Customer_119,32,73229.0,18614.0,733,6,Salaried,B,West,284137.0,35612.0,69823.0,21822.0,36737.0,2009.0,0
119,120,CUST0120,Customer_120,26,57798.0,8814.0,601,2,Salaried,D,West,123377.0,12499.0,79916.0,18707.0,32426.0,810.0,1
120,121,CUST0121,Customer_121,41,61332.0,28802.0,565,1,Self-Employed,A,East,236855.0,27934.0,66564.0,8884.0,13538.0,2889.0,0
121,122,CUST0122,Customer_122,52,55957.0,26873.0,675,7,Salaried,C,West,135537.0,38698.0,86127.0,6877.0,8976.0,4209.0,0
122,123,CUST0123,Customer_123,51,55002.0,16084.0,687,8,Salaried,C,West,150885.0,25849.0,57135.0,13248.0,24703.0,1341.0,1
123,124,CUST0124,Customer_124,43,42012.0,10165.0,625,2,Unemployed,A,South,114315.0,16724.0,61817.0,4321.0,5330.0,1493.0,0
124,125,CUST0125,Customer_125,61,60697.0,24581.0,746,10,Salaried,B,North,243312.0,35174.0,64043.0,7838.0,11566.0,1465.0,0
125,126,CUST0126,Customer_126,47,53249.0,20256.0,573,4,Salaried,A,South,166818.0,49628.0,69817.0,4762.0,6163.0,3029.0,1
126,127,CUST0127,Customer_127,24,NaN,622.0,647,4,Salaried,A,East,256210.0,16464.0,162059.0,34789.0,48382.0,100.0,0
127,128,CUST0128,Customer_128,56,83320.0,17184.0,633,3,Salaried,B,East,373622.0,34530.0,98427.0,9656.0,17755.0,1757.0,0
128,129,CUST0129,Customer_129,48,61945.0,21144.0,676,5,Salaried,A,North,216921.0,37052.0,103804.0,24199.0,44247.0,3043.0,0
129,130,CUST0130,Customer_130,50,41265.0,NaN,702,2,Self-Employed,C,East,92781.0,27560.0,73738.0,21182.0,34337.0,1217.0,1
130,131,CUST0131,Customer_131,47,34977.0,20278.0,599,5,Self-Employed,D,North,162654.0,28947.0,58581.0,17373.0,22414.0,3125.0,0
131,132,CUST0132,Customer_132,47,NaN,542.0,738,3,Salaried,C,East,206335.0,500.0,73832.0,10548.0,17229.0,100.0,0
132,133,CUST0133,Customer_133,25,59729.0,34034.0,685,1,Salaried,A,East,97742.0,42714.0,96741.0,20769.0,32249.0,3844.0,1
133,134,CUST0134,Customer_134,47,63643.0,32975.0,529,4,Self-Employed,A,East,205637.0,48657.0,52960.0,11593.0,22264.0,4990.0,0
134,135,CUST0135,Customer_135,58,23597.0,14970.0,523,7,Salaried,A,South,45631.0,18181.0,28158.0,5403.0,9612.0,1318.0,1
135,136,CUST0136,Customer_136,35,71694.0,22361.0,679,8,Salaried,A,South,167379.0,31126.0,119782.0,29530.0,49952.0,3455.0,0
136,137,CUST0137,Customer_137,49,63180.0,500.0,662,4,Salaried,D,East,259979.0,5658.0,94059.0,10631.0,17934.0,100.0,1
137,138,CUST0138,Customer_138,22,35012.0,4124.0,672,4,Self-Employed,B,East,68541.0,24638.0,46662.0,16041.0,34750.0,638.0,0
138,139,CUST0139,Customer_139,37,46513.0,14475.0,678,8,Salaried,A,West,201136.0,29721.0,55251.0,4388.0,8584.0,887.0,0
139,140,CUST0140,Customer_140,41,59747.0,5134.0,698,7,Self-Employed,C,South,285541.0,19695.0,96330.0,28780.0,48839.0,286.0,0
140,141,CUST0141,Customer_141,67,55944.0,26573.0,756,9,Salaried,B,South,202677.0,40924.0,84451.0,19274.0,32365.0,4775.0,0
141,142,CUST0142,Customer_142,31,49741.0,41968.0,591,10,Salaried,A,South,198280.0,51707.0,63092.0,7789.0,9553.0,6842.0,0
142,143,CUST0143,Customer_143,33,53137.0,3881.0,586,9,Salaried,A,East,212418.0,15264.0,89934.0,24615.0,52738.0,639.0,0
143,144,CUST0144,Customer_144,40,NaN,7950.0,593,10,Salaried,B,North,251050.0,9654.0,51975.0,3916.0,5949.0,1381.0,0
144,145,CUST0145,Customer_145,67,57746.0,20825.0,703,5,Salaried,C,South,155648.0,15520.0,56036.0,15820.0,23033.0,2228.0,0
145,146,CUST0146,Customer_146,61,81487.0,37333.0,780,4,Salaried,A,North,168678.0,48384.0,117570.0,26688.0,58698.0,3259.0,0
146,147,CUST0147,Customer_147,22,12000.0,3332.0,645,4,Salaried,D,East,39805.0,15600.0,21264.0,1770.0,3396.0,223.0,0
147,148,CUST0148,Customer_148,31,50737.0,20988.0,480,3,Salaried,C,West,170800.0,39453.0,53135.0,3924.0,4895.0,2417.0,0
148,149,CUST0149,Customer_149,59,58177.0,39856.0,544,8,Salaried,C,West,123492.0,60855.0,61067.0,16809.0,21211.0,3133.0,1
149,150,CUST0150,Customer_150,23,60328.0,500.0,613,8,Salaried,A,South,219949.0,21490.0,56678.0,7815.0,9577.0,100.0,0
150,151,CUST0151,Customer_151,61,48306.0,2627.0,635,9,Unemployed,A,North,74847.0,5641.0,80215.0,25411.0,45730.0,133.0,0
151,152,CUST0152,Customer_152,34,23379.0,12917.0,647,2,Salaried,C,North,110976.0,20451.0,23996.0,6686.0,8502.0,886.0,0
152,153,CUST0153,Customer_153,64,60904.0,11753.0,683,5,Self-Employed,B,North,147754.0,25115.0,79369.0,20593.0,43933.0,964.0,0
153,154,CUST0154,Customer_154,34,86092.0,27751.0,655,3,Unemployed,B,West,141058.0,55474.0,154180.0,20596.0,44012.0,2105.0,0
154,155,CUST0155,Customer_155,41,27390.0,20900.0,764,9,Salaried,C,West,51462.0,41261.0,22245.0,5843.0,10202.0,1658.0,1
155,156,CUST0156,Customer_156,52,70549.0,500.0,626,3,Self-Employed,A,East,165146.0,18336.0,95699.0,32006.0,58143.0,100.0,0
156,157,CUST0157,Customer_157,26,49087.0,24185.0,611,2,Self-Employed,C,North,120689.0,31470.0,64416.0,4990.0,7445.0,2239.0,0

In [10]:
df. iloc [0:5 , 2]

0    Customer_001
1    Customer_002
2    Customer_003
3    Customer_004
4    Customer_005
Name: name, dtype: str

In [11]:
df.isnull().sum()

id                   0
customer_id          0
name                 0
age                  0
income              15
debt                 9
credit_score         0
num_accounts         0
employment_type      0
risk_grade           0
region               0
credit_limit         0
used_credit          0
revenue              0
profit               0
ebitda               0
interest_expense     0
default              0
dtype: int64

In [12]:
df.fillna(0,inplace=True)

,id,customer_id,name,age,income,debt,credit_score,num_accounts,employment_type,risk_grade,region,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default
0,1,CUST0001,Customer_001,25,52466.0,13887.0,775,5,Salaried,A,South,214544.0,30744.0,73659.0,15290.0,32354.0,2107.0,0
1,2,CUST0002,Customer_002,57,74188.0,500.0,598,2,Self-Employed,A,East,130761.0,19542.0,88734.0,12895.0,19499.0,100.0,0
2,3,CUST0003,Customer_003,51,57827.0,30807.0,531,10,Self-Employed,A,North,234444.0,53255.0,48647.0,3954.0,8629.0,5154.0,0
3,4,CUST0004,Customer_004,41,52145.0,14022.0,688,9,Salaried,B,West,233162.0,17957.0,46928.0,8187.0,17720.0,738.0,0
4,5,CUST0005,Customer_005,41,36358.0,31375.0,754,9,Self-Employed,D,West,114660.0,41472.0,52901.0,4611.0,6191.0,4798.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,CUST0296,Customer_296,45,61515.0,500.0,759,4,Salaried,A,East,184659.0,21152.0,77380.0,5499.0,6792.0,100.0,0
296,297,CUST0297,Customer_297,60,78772.0,30021.0,635,1,Unemployed,C,East,310686.0,42533.0,95663.0,6416.0,14057.0,3497.0,1
297,38,CUST0038,Customer_038,59,62718.0,35199.0,685,7,Salaried,C,North,192065.0,44816.0,92032.0,21804.0,34626.0,5677.0,1
298,129,CUST0129,Customer_129,48,61945.0,21144.0,676,5,Salaried,A,North,216921.0,37052.0,103804.0,24199.0,44247.0,3043.0,0
299,242,CUST0242,Customer_242,48,59973.0,12251.0,698,10,Salaried,D,North,213307.0,26039.0,62658.0,21167.0,39116.0,1089.0,1

In [13]:
df.isnull().sum()

id                  0
customer_id         0
name                0
age                 0
income              0
debt                0
credit_score        0
num_accounts        0
employment_type     0
risk_grade          0
region              0
credit_limit        0
used_credit         0
revenue             0
profit              0
ebitda              0
interest_expense    0
default             0
dtype: int64

In [14]:
df.rename(columns={"num_accounts":"account_count"},inplace=True)

In [15]:
df

,id,customer_id,name,age,income,debt,credit_score,account_count,employment_type,risk_grade,region,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default
0,1,CUST0001,Customer_001,25,52466.0,13887.0,775,5,Salaried,A,South,214544.0,30744.0,73659.0,15290.0,32354.0,2107.0,0
1,2,CUST0002,Customer_002,57,74188.0,500.0,598,2,Self-Employed,A,East,130761.0,19542.0,88734.0,12895.0,19499.0,100.0,0
2,3,CUST0003,Customer_003,51,57827.0,30807.0,531,10,Self-Employed,A,North,234444.0,53255.0,48647.0,3954.0,8629.0,5154.0,0
3,4,CUST0004,Customer_004,41,52145.0,14022.0,688,9,Salaried,B,West,233162.0,17957.0,46928.0,8187.0,17720.0,738.0,0
4,5,CUST0005,Customer_005,41,36358.0,31375.0,754,9,Self-Employed,D,West,114660.0,41472.0,52901.0,4611.0,6191.0,4798.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,CUST0296,Customer_296,45,61515.0,500.0,759,4,Salaried,A,East,184659.0,21152.0,77380.0,5499.0,6792.0,100.0,0
296,297,CUST0297,Customer_297,60,78772.0,30021.0,635,1,Unemployed,C,East,310686.0,42533.0,95663.0,6416.0,14057.0,3497.0,1
297,38,CUST0038,Customer_038,59,62718.0,35199.0,685,7,Salaried,C,North,192065.0,44816.0,92032.0,21804.0,34626.0,5677.0,1
298,129,CUST0129,Customer_129,48,61945.0,21144.0,676,5,Salaried,A,North,216921.0,37052.0,103804.0,24199.0,44247.0,3043.0,0
299,242,CUST0242,Customer_242,48,59973.0,12251.0,698,10,Salaried,D,North,213307.0,26039.0,62658.0,21167.0,39116.0,1089.0,1

In [16]:
df["employment_type"].value_counts()

employment_type
Salaried         193
Self-Employed     69
Unemployed        38
Name: count, dtype: int64

In [17]:
df.groupby("employment_type")["credit_score"].mean()

employment_type
Salaried         681.367876
Self-Employed    672.710145
Unemployed       688.763158
Name: credit_score, dtype: float64

In [19]:
df.sort_values("income",ascending=False)

,id,customer_id,name,age,income,debt,credit_score,account_count,employment_type,risk_grade,region,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default
101,102,CUST0102,Customer_102,30,107291.0,16090.0,820,6,Salaried,A,West,500000.0,35671.0,172290.0,13823.0,17182.0,1847.0,0
79,80,CUST0080,Customer_080,52,100315.0,15704.0,642,5,Salaried,A,West,476704.0,28831.0,166816.0,57716.0,85700.0,2225.0,0
228,229,CUST0229,Customer_229,46,96898.0,9434.0,683,4,Salaried,C,South,389883.0,18526.0,149207.0,48601.0,85002.0,1069.0,0
97,98,CUST0098,Customer_098,53,93326.0,8085.0,827,5,Self-Employed,A,East,226813.0,27122.0,111669.0,13890.0,27836.0,766.0,0
15,16,CUST0016,Customer_016,57,93312.0,17690.0,606,9,Salaried,C,East,210265.0,28746.0,161074.0,21322.0,46580.0,1895.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,53,CUST0053,Customer_053,38,0.0,500.0,711,9,Salaried,B,North,129038.0,9135.0,51927.0,13088.0,20309.0,100.0,0
23,24,CUST0024,Customer_024,64,0.0,41247.0,707,10,Salaried,A,East,169625.0,44783.0,41744.0,8955.0,13050.0,7060.0,0
252,253,CUST0253,Customer_253,29,0.0,500.0,785,3,Salaried,B,East,80361.0,2178.0,45809.0,11312.0,21027.0,100.0,0
51,52,CUST0052,Customer_052,30,0.0,29227.0,721,3,Salaried,B,North,182655.0,40194.0,71065.0,14925.0,19333.0,3348.0,0
272,273,CUST0273,Customer_273,28,0.0,500.0,548,3,Self-Employed,C,East,156956.0,10249.0,115066.0,7236.0,12754.0,100.0,1

In [22]:
data2=pd.read_csv("customer_additional_data.csv")
df2=pd.DataFrame(data2)
df2

df

,id,customer_id,name,age,income,debt,credit_score,account_count,employment_type,risk_grade,region,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default
0,1,CUST0001,Customer_001,25,52466.0,13887.0,775,5,Salaried,A,South,214544.0,30744.0,73659.0,15290.0,32354.0,2107.0,0
1,2,CUST0002,Customer_002,57,74188.0,500.0,598,2,Self-Employed,A,East,130761.0,19542.0,88734.0,12895.0,19499.0,100.0,0
2,3,CUST0003,Customer_003,51,57827.0,30807.0,531,10,Self-Employed,A,North,234444.0,53255.0,48647.0,3954.0,8629.0,5154.0,0
3,4,CUST0004,Customer_004,41,52145.0,14022.0,688,9,Salaried,B,West,233162.0,17957.0,46928.0,8187.0,17720.0,738.0,0
4,5,CUST0005,Customer_005,41,36358.0,31375.0,754,9,Self-Employed,D,West,114660.0,41472.0,52901.0,4611.0,6191.0,4798.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,CUST0296,Customer_296,45,61515.0,500.0,759,4,Salaried,A,East,184659.0,21152.0,77380.0,5499.0,6792.0,100.0,0
296,297,CUST0297,Customer_297,60,78772.0,30021.0,635,1,Unemployed,C,East,310686.0,42533.0,95663.0,6416.0,14057.0,3497.0,1
297,38,CUST0038,Customer_038,59,62718.0,35199.0,685,7,Salaried,C,North,192065.0,44816.0,92032.0,21804.0,34626.0,5677.0,1
298,129,CUST0129,Customer_129,48,61945.0,21144.0,676,5,Salaried,A,North,216921.0,37052.0,103804.0,24199.0,44247.0,3043.0,0
299,242,CUST0242,Customer_242,48,59973.0,12251.0,698,10,Salaried,D,North,213307.0,26039.0,62658.0,21167.0,39116.0,1089.0,1

In [23]:
merged=df.merge(df2,on="customer_id",how="left")
merged

,id,customer_id,name,age,income,debt,credit_score,account_count,employment_type,risk_grade,...,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default,city,loyalty_points,membership
0,1,CUST0001,Customer_001,25,52466.0,13887.0,775,5,Salaried,A,...,214544.0,30744.0,73659.0,15290.0,32354.0,2107.0,0,Mumbai,1224.0,Platinum
1,2,CUST0002,Customer_002,57,74188.0,500.0,598,2,Self-Employed,A,...,130761.0,19542.0,88734.0,12895.0,19499.0,100.0,0,Chennai,3380.0,Gold
2,3,CUST0003,Customer_003,51,57827.0,30807.0,531,10,Self-Employed,A,...,234444.0,53255.0,48647.0,3954.0,8629.0,5154.0,0,Hyderabad,3987.0,Gold
3,4,CUST0004,Customer_004,41,52145.0,14022.0,688,9,Salaried,B,...,233162.0,17957.0,46928.0,8187.0,17720.0,738.0,0,Delhi,4585.0,Gold
4,5,CUST0005,Customer_005,41,36358.0,31375.0,754,9,Self-Employed,D,...,114660.0,41472.0,52901.0,4611.0,6191.0,4798.0,1,Chennai,3856.0,Silver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,CUST0296,Customer_296,45,61515.0,500.0,759,4,Salaried,A,...,184659.0,21152.0,77380.0,5499.0,6792.0,100.0,0,NaN,NaN,NaN
296,297,CUST0297,Customer_297,60,78772.0,30021.0,635,1,Unemployed,C,...,310686.0,42533.0,95663.0,6416.0,14057.0,3497.0,1,NaN,NaN,NaN
297,38,CUST0038,Customer_038,59,62718.0,35199.0,685,7,Salaried,C,...,192065.0,44816.0,92032.0,21804.0,34626.0,5677.0,1,Hyderabad,4514.0,Silver
298,129,CUST0129,Customer_129,48,61945.0,21144.0,676,5,Salaried,A,...,216921.0,37052.0,103804.0,24199.0,44247.0,3043.0,0,Delhi,2824.0,Basic
299,242,CUST0242,Customer_242,48,59973.0,12251.0,698,10,Salaried,D,...,213307.0,26039.0,62658.0,21167.0,39116.0,1089.0,1,Delhi,1652.0,Basic

In [25]:
df.corr(numeric_only=True)

,id,age,income,debt,credit_score,account_count,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default
id,1.000000,-0.070946,-0.013412,-0.079465,-0.034641,-0.081002,0.002083,-0.065171,-0.039022,-0.000717,0.005017,-0.093920,-0.011124
age,-0.070946,1.000000,0.076608,0.147815,-0.055415,0.051852,0.023427,0.079528,0.014004,0.036605,0.024303,0.140622,0.072674
income,-0.013412,0.076608,1.000000,0.067482,0.029927,-0.120147,0.621185,0.098064,0.660076,0.414471,0.409662,0.091138,0.087236
debt,-0.079465,0.147815,0.067482,1.000000,-0.095300,0.144114,0.064824,0.790950,0.038728,0.029722,0.035027,0.808303,0.114100
credit_score,-0.034641,-0.055415,0.029927,-0.095300,1.000000,0.005784,0.069736,-0.110543,0.016857,0.029687,-0.001881,-0.102813,-0.106601
account_count,-0.081002,0.051852,-0.120147,0.144114,0.005784,1.000000,-0.023907,0.118287,-0.116185,-0.056170,-0.048756,0.055964,0.045318
credit_limit,0.002083,0.023427,0.621185,0.064824,0.069736,-0.023907,1.000000,0.062110,0.565694,0.376720,0.349158,0.068124,0.032735
used_credit,-0.065171,0.079528,0.098064,0.790950,-0.110543,0.118287,0.062110,1.000000,0.061294,0.010913,0.003144,0.729926,0.154591
revenue,-0.039022,0.014004,0.660076,0.038728,0.016857,-0.116185,0.565694,0.061294,1.000000,0.634668,0.605346,0.059008,0.061492
profit,-0.000717,0.036605,0.414471,0.029722,0.029687,-0.056170,0.376720,0.010913,0.634668,1.000000,0.947731,0.051328,0.035278
ebitda,0.005017,0.024303,0.409662,0.035027,-0.001881,-0.048756,0.349158,0.003144,0.605346,0.947731,1.000000,0.044014,0.027672
interest_expense,-0.093920,0.140622,0.091138,0.808303,-0.102813,0.055964,0.068124,0.729926,0.059008,0.051328,0.044014,1.000000,0.119255
default,-0.011124,0.072674,0.087236,0.114100,-0.106601,0.045318,0.032735,0.154591,0.061492,0.035278,0.027672,0.119255,1.000000

In [26]:
high_risk=df[df["credit_score"]<600]
high_risk

,id,customer_id,name,age,income,debt,credit_score,account_count,employment_type,risk_grade,region,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default
1,2,CUST0002,Customer_002,57,74188.0,500.0,598,2,Self-Employed,A,East,130761.0,19542.0,88734.0,12895.0,19499.0,100.0,0
2,3,CUST0003,Customer_003,51,57827.0,30807.0,531,10,Self-Employed,A,North,234444.0,53255.0,48647.0,3954.0,8629.0,5154.0,0
11,12,CUST0012,Customer_012,66,46013.0,19922.0,599,5,Salaried,A,West,104382.0,30524.0,65335.0,3664.0,6610.0,2601.0,0
24,25,CUST0025,Customer_025,57,63029.0,31272.0,537,10,Salaried,B,East,312346.0,33964.0,78855.0,9190.0,15545.0,3858.0,0
27,28,CUST0028,Customer_028,59,31997.0,13115.0,578,10,Self-Employed,B,West,123498.0,16797.0,54175.0,4469.0,5723.0,2085.0,1
35,36,CUST0036,Customer_036,23,47603.0,49172.0,593,7,Self-Employed,B,South,158054.0,48097.0,83337.0,28530.0,54205.0,6219.0,0
38,39,CUST0039,Customer_039,34,82644.0,19098.0,576,7,Unemployed,D,South,399618.0,37258.0,103862.0,18282.0,32085.0,2469.0,1
47,48,CUST0048,Customer_048,62,35073.0,22398.0,593,3,Salaried,B,West,87790.0,39990.0,56792.0,18563.0,30011.0,1122.0,0
50,51,CUST0051,Customer_051,56,47897.0,14296.0,580,9,Salaried,B,East,141308.0,18803.0,51304.0,4861.0,6365.0,1769.0,0
53,54,CUST0054,Customer_054,42,61076.0,13973.0,537,6,Salaried,B,East,98464.0,27316.0,101440.0,18957.0,36042.0,1936.0,0
60,61,CUST0061,Customer_061,64,33061.0,0.0,593,8,Salaried,D,South,102420.0,2867.0,45334.0,2368.0,3506.0,100.0,0
66,67,CUST0067,Customer_067,63,46285.0,500.0,580,8,Salaried,B,South,72964.0,23703.0,40843.0,9249.0,12384.0,100.0,0
78,79,CUST0079,Customer_079,47,59108.0,34029.0,589,5,Salaried,A,South,219482.0,32967.0,81266.0,4336.0,9340.0,2429.0,0
81,82,CUST0082,Customer_082,41,39642.0,12690.0,587,9,Self-Employed,A,West,65338.0,31109.0,66663.0,19630.0,29878.0,1011.0,0
82,83,CUST0083,Customer_083,28,49827.0,35461.0,511,10,Salaried,D,West,152335.0,42475.0,76206.0,7666.0,16085.0,4503.0,1
83,84,CUST0084,Customer_084,60,28658.0,0.0,531,3,Self-Employed,A,North,97852.0,37733.0,45817.0,6189.0,10911.0,1372.0,0
88,89,CUST0089,Customer_089,57,43225.0,12617.0,466,2,Unemployed,D,East,133296.0,20474.0,69762.0,21807.0,33704.0,1000.0,1
91,92,CUST0092,Customer_092,58,35877.0,25650.0,590,3,Salaried,B,East,114064.0,16311.0,61958.0,5848.0,9781.0,2883.0,0
117,118,CUST0118,Customer_118,27,63488.0,22012.0,525,1,Self-Employed,B,West,139714.0,33198.0,104987.0,27805.0,56161.0,1979.0,0
120,121,CUST0121,Customer_121,41,61332.0,28802.0,565,1,Self-Employed,A,East,236855.0,27934.0,66564.0,8884.0,13538.0,2889.0,0
125,126,CUST0126,Customer_126,47,53249.0,20256.0,573,4,Salaried,A,South,166818.0,49628.0,69817.0,4762.0,6163.0,3029.0,1
130,131,CUST0131,Customer_131,47,34977.0,20278.0,599,5,Self-Employed,D,North,162654.0,28947.0,58581.0,17373.0,22414.0,3125.0,0
133,134,CUST0134,Customer_134,47,63643.0,32975.0,529,4,Self-Employed,A,East,205637.0,48657.0,52960.0,11593.0,22264.0,4990.0,0
134,135,CUST0135,Customer_135,58,23597.0,14970.0,523,7,Salaried,A,South,45631.0,18181.0,28158.0,5403.0,9612.0,1318.0,1
141,142,CUST0142,Customer_142,31,49741.0,41968.0,591,10,Salaried,A,South,198280.0,51707.0,63092.0,7789.0,9553.0,6842.0,0
142,143,CUST0143,Customer_143,33,53137.0,3881.0,586,9,Salaried,A,East,212418.0,15264.0,89934.0,24615.0,52738.0,639.0,0
143,144,CUST0144,Customer_144,40,0.0,7950.0,593,10,Salaried,B,North,251050.0,9654.0,51975.0,3916.0,5949.0,1381.0,0
147,148,CUST0148,Customer_148,31,50737.0,20988.0,480,3,Salaried,C,West,170800.0,39453.0,53135.0,3924.0,4895.0,2417.0,0
148,149,CUST0149,Customer_149,59,58177.0,39856.0,544,8,Salaried,C,West,123492.0,60855.0,61067.0,16809.0,21211.0,3133.0,1
158,159,CUST0159,Customer_159,44,36048.0,33293.0,557,9,Salaried,C,West,89318.0,48815.0,41646.0,5014.0,9714.0,5518.0,1
166,167,CUST0167,Customer_167,36,62902.0,5588.0,578,1,Salaried,A,East,138850.0,10695.0,50492.0,15547.0,28052.0,481.0,0
168,169,CUST0169,Customer_169,36,49662.0,915.0,594,1,Salaried,B,North,246713.0,10308.0,67294.0,10996.0,17665.0,145.0,0
178,179,CUST0179,Customer_179,63,68154.0,21227.0,530,7,Salaried,A,East,285161.0,30912.0,66449.0,15992.0,27581.0,2208.0,0
195,196,CUST0196,Customer_196,25,56297.0,24294.0,588,5,Salaried,D,West,92811.0,36329.0,74599.0,17546.0,26827.0,2154.0,1
206,207,CUST0207,Customer_207,56,69648.0,40174.0,446,8,Salaried,B,North,206304.0,45749.0,66986.0,7006.0,10612.0,6753.0,0
208,209,CUST0209,Customer_209,33,59192.0,38015.0,388,5,Salaried,B,West,192929.0,31725.0,99882.0,18432.0,34911.0,5259.0,0
209,210,CUST0210,Customer_210,57,59219.0,4755.0,542,4,Unemployed,C,West,120292.0,1727.0,50270.0,2759.0,5097.0,386.0,0
212,213,CUST0213,Customer_213,58,52344.0,7571.0,587,3,Salaried,D,East,154254.0,14521.0,75825.0,20250.0,42377.0,505.0,1
224,225,CUST0225,Customer_225,54,78921.0,11727.0,571,2,Salaried,A,South,191152.0,15021.0,136925.0,19838.0,42104.0,668.0,0
234,235,CUST0235,Customer_235,44,78572.0,22652.0,597,7,Salaried,D,East,188962.0,50877.0,116246.0,7468.0,16236.0,2256.0,1
237,238,CUST0238,Customer_238,41,26177.0,25501.0,567,10,Unemployed,B,West,125118.0,40884.0,33833.0,4307.0,9161.0,1581.0,1
240,241,CUST0241,Customer_241,27,64435.0,12775.0,558,9,Salaried,D,North,169556.0,19953.0,59217.0,6432.0,12169.0,1342.0,1
245,246,CUST0246,Customer_246,24,46508.0,12903.0,568,5,Salaried,A,East,86716.0,29875.0,44915.0,6712.0,14144.0,2127.0,0
269,270,CUST0270,Customer_270,48,74606.0,17855.0,581,4,Salaried,C,West,359935.0,40571.0,121340.0,21603.0,44901.0,2795.0,0
272,273,CUST0273,Customer_273,28,0.0,500.0,548,3,Self-Employed,C,East,156956.0,10249.0,115066.0,7236.0,12754.0,100.0,1
273,274,CUST0274,Customer_274,66,56658.0,26229.0,596,3,Salaried,B,North,148476.0,35527.0,60651.0,16158.0,28399.0,3731.0,1
274,275,CUST0275,Customer_275,40,39927.0,13789.0,598,5,Self-Employed,A,West,111365.0,22989.0,46783.0,13020.0,28444.0,2046.0,0
283,284,CUST0284,Customer_284,44,36270.0,27208.0,511,8,Self-Employed,B,East,133993.0,44843.0,31345.0,9344.0,12968.0,4175.0,0
285,286,CUST0286,Customer_286,65,52640.0,4566.0,506,2,Self-Employed,C,North,142593.0,13711.0,61929.0,16753.0,26208.0,354.0,1

In [30]:
df.duplicated().sum()
df.drop_duplicates( inplace = True )

df

,id,customer_id,name,age,income,debt,credit_score,account_count,employment_type,risk_grade,region,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default
0,1,CUST0001,Customer_001,25,52466.0,13887.0,775,5,Salaried,A,South,214544.0,30744.0,73659.0,15290.0,32354.0,2107.0,0
1,2,CUST0002,Customer_002,57,74188.0,500.0,598,2,Self-Employed,A,East,130761.0,19542.0,88734.0,12895.0,19499.0,100.0,0
2,3,CUST0003,Customer_003,51,57827.0,30807.0,531,10,Self-Employed,A,North,234444.0,53255.0,48647.0,3954.0,8629.0,5154.0,0
3,4,CUST0004,Customer_004,41,52145.0,14022.0,688,9,Salaried,B,West,233162.0,17957.0,46928.0,8187.0,17720.0,738.0,0
4,5,CUST0005,Customer_005,41,36358.0,31375.0,754,9,Self-Employed,D,West,114660.0,41472.0,52901.0,4611.0,6191.0,4798.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,293,CUST0293,Customer_293,65,62702.0,27333.0,719,7,Self-Employed,A,South,293714.0,40724.0,91599.0,7982.0,15101.0,4481.0,0
293,294,CUST0294,Customer_294,36,51594.0,27684.0,638,9,Self-Employed,B,South,220712.0,46208.0,63547.0,6726.0,11833.0,2498.0,0
294,295,CUST0295,Customer_295,46,60916.0,500.0,680,1,Salaried,C,East,103893.0,16936.0,94285.0,14098.0,16932.0,100.0,0
295,296,CUST0296,Customer_296,45,61515.0,500.0,759,4,Salaried,A,East,184659.0,21152.0,77380.0,5499.0,6792.0,100.0,0
296,297,CUST0297,Customer_297,60,78772.0,30021.0,635,1,Unemployed,C,East,310686.0,42533.0,95663.0,6416.0,14057.0,3497.0,1

In [33]:
df["debt_ratio"]=df["debt"]/df["income"]
df["utilization"]=df["used_credit"]/df["credit_limit"]
df["profit_margin"]=df["profit"]/df["revenue"]
df

,id,customer_id,name,age,income,debt,credit_score,account_count,employment_type,risk_grade,...,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default,debt_ratio,utilization,profit_margin
0,1,CUST0001,Customer_001,25,52466.0,13887.0,775,5,Salaried,A,...,214544.0,30744.0,73659.0,15290.0,32354.0,2107.0,0,0.264686,0.143299,0.207578
1,2,CUST0002,Customer_002,57,74188.0,500.0,598,2,Self-Employed,A,...,130761.0,19542.0,88734.0,12895.0,19499.0,100.0,0,0.006740,0.149448,0.145322
2,3,CUST0003,Customer_003,51,57827.0,30807.0,531,10,Self-Employed,A,...,234444.0,53255.0,48647.0,3954.0,8629.0,5154.0,0,0.532744,0.227154,0.081279
3,4,CUST0004,Customer_004,41,52145.0,14022.0,688,9,Salaried,B,...,233162.0,17957.0,46928.0,8187.0,17720.0,738.0,0,0.268904,0.077015,0.174459
4,5,CUST0005,Customer_005,41,36358.0,31375.0,754,9,Self-Employed,D,...,114660.0,41472.0,52901.0,4611.0,6191.0,4798.0,1,0.862946,0.361695,0.087163
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,293,CUST0293,Customer_293,65,62702.0,27333.0,719,7,Self-Employed,A,...,293714.0,40724.0,91599.0,7982.0,15101.0,4481.0,0,0.435919,0.138652,0.087141
293,294,CUST0294,Customer_294,36,51594.0,27684.0,638,9,Self-Employed,B,...,220712.0,46208.0,63547.0,6726.0,11833.0,2498.0,0,0.536574,0.209359,0.105843
294,295,CUST0295,Customer_295,46,60916.0,500.0,680,1,Salaried,C,...,103893.0,16936.0,94285.0,14098.0,16932.0,100.0,0,0.008208,0.163014,0.149525
295,296,CUST0296,Customer_296,45,61515.0,500.0,759,4,Salaried,A,...,184659.0,21152.0,77380.0,5499.0,6792.0,100.0,0,0.008128,0.114546,0.071065
296,297,CUST0297,Customer_297,60,78772.0,30021.0,635,1,Unemployed,C,...,310686.0,42533.0,95663.0,6416.0,14057.0,3497.0,1,0.381113,0.136900,0.067069

In [35]:
df["risk_grade"].unique()
df["risk_grade"].value_counts()

risk_grade
A    93
B    93
C    73
D    38
Name: count, dtype: int64

In [36]:
# Now this is a pipeline for data preparation

In [38]:
import pandas as pd

data=pd.read_csv("credit_data.csv")
df=pd.DataFrame(data)

df.drop(columns={"customer_id","name"},inplace=True)
df

,id,age,income,debt,credit_score,num_accounts,employment_type,risk_grade,region,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default
0,1,25,52466.0,13887.0,775,5,Salaried,A,South,214544.0,30744.0,73659.0,15290.0,32354.0,2107.0,0
1,2,57,74188.0,500.0,598,2,Self-Employed,A,East,130761.0,19542.0,88734.0,12895.0,19499.0,100.0,0
2,3,51,57827.0,30807.0,531,10,Self-Employed,A,North,234444.0,53255.0,48647.0,3954.0,8629.0,5154.0,0
3,4,41,52145.0,14022.0,688,9,Salaried,B,West,233162.0,17957.0,46928.0,8187.0,17720.0,738.0,0
4,5,41,36358.0,31375.0,754,9,Self-Employed,D,West,114660.0,41472.0,52901.0,4611.0,6191.0,4798.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,45,61515.0,500.0,759,4,Salaried,A,East,184659.0,21152.0,77380.0,5499.0,6792.0,100.0,0
296,297,60,78772.0,30021.0,635,1,Unemployed,C,East,310686.0,42533.0,95663.0,6416.0,14057.0,3497.0,1
297,38,59,62718.0,35199.0,685,7,Salaried,C,North,192065.0,44816.0,92032.0,21804.0,34626.0,5677.0,1
298,129,48,61945.0,21144.0,676,5,Salaried,A,North,216921.0,37052.0,103804.0,24199.0,44247.0,3043.0,0
299,242,48,59973.0,12251.0,698,10,Salaried,D,North,213307.0,26039.0,62658.0,21167.0,39116.0,1089.0,1

In [52]:
df["income"]=df["income"].fillna(df["income"].median())
df.isnull().sum()

df["employment_type"]=df["employment_type"].fillna("Unknown")
df.drop_duplicates(inplace=True)

df

,id,age,income,debt,credit_score,num_accounts,employment_type,risk_grade,region,credit_limit,used_credit,revenue,profit,ebitda,interest_expense,default
0,1,25,52466.0,13887.0,775,5,Salaried,A,South,214544.0,30744.0,73659.0,15290.0,32354.0,2107.0,0
1,2,57,74188.0,500.0,598,2,Self-Employed,A,East,130761.0,19542.0,88734.0,12895.0,19499.0,100.0,0
2,3,51,57827.0,30807.0,531,10,Self-Employed,A,North,234444.0,53255.0,48647.0,3954.0,8629.0,5154.0,0
3,4,41,52145.0,14022.0,688,9,Salaried,B,West,233162.0,17957.0,46928.0,8187.0,17720.0,738.0,0
4,5,41,36358.0,31375.0,754,9,Self-Employed,D,West,114660.0,41472.0,52901.0,4611.0,6191.0,4798.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,293,65,62702.0,27333.0,719,7,Self-Employed,A,South,293714.0,40724.0,91599.0,7982.0,15101.0,4481.0,0
293,294,36,51594.0,27684.0,638,9,Self-Employed,B,South,220712.0,46208.0,63547.0,6726.0,11833.0,2498.0,0
294,295,46,60916.0,500.0,680,1,Salaried,C,East,103893.0,16936.0,94285.0,14098.0,16932.0,100.0,0
295,296,45,61515.0,500.0,759,4,Salaried,A,East,184659.0,21152.0,77380.0,5499.0,6792.0,100.0,0
296,297,60,78772.0,30021.0,635,1,Unemployed,C,East,310686.0,42533.0,95663.0,6416.0,14057.0,3497.0,1

In [53]:
df["debt_ratio"]=df["debt"]/df["income"]
print(df.describe())
print(df["default"].value_counts())

               id         age         income          debt  credit_score  \
count  297.000000  297.000000     297.000000    288.000000    297.000000
mean   149.000000   44.087542   54874.215488  17527.180556    680.252525
std     85.880731   12.780861   17344.234079  11256.918609     78.114782
min      1.000000   21.000000   12000.000000    500.000000    388.000000
25%     75.000000   34.000000   43223.000000   8501.000000    635.000000
50%    149.000000   44.000000   55590.000000  16961.000000    683.000000
75%    223.000000   55.000000   64541.000000  24978.000000    729.000000
max    297.000000   67.000000  107291.000000  49172.000000    850.000000

       num_accounts  credit_limit   used_credit        revenue        profit  \
count    297.000000     297.00000    297.000000     297.000000    297.000000
mean       5.313131  176135.86532  27605.875421   72716.043771  14148.518519
std        2.861604   84799.26468  13659.899641   30148.290583   9027.448090
min        1.000000   21255.00000    500.000000   16085.000000   1709.000000
25%        3.000000  114660.00000  16797.000000   51304.000000   7236.000000
50%        5.000000  162182.00000  27713.000000   66986.000000  12492.000000
75%        8.000000  219949.00000  37442.000000   91599.000000  18957.000000
max       10.000000  500000.00000  64785.000000  172290.000000  57716.000000

             ebitda  interest_expense     default  debt_ratio
count    297.000000        297.000000  297.000000  288.000000
mean   23488.861953       2070.205387    0.239057    0.369198
std    15315.788219       1570.990390    0.427228    0.328698
min     3108.000000        100.000000    0.000000    0.006224
25%    12059.000000        927.000000    0.000000    0.155534
50%    19635.000000       1895.000000    0.000000    0.311676
75%    31695.000000       2828.000000    0.000000    0.493561
max    85700.000000       8097.000000    1.000000    2.681473
default
0    226
1     71
Name: count, dtype: int64

In [55]:
X=df.drop(columns={"default"})
Y=df["default"]

X,Y

(      id  age   income     debt  credit_score  num_accounts employment_type  \
 0      1   25  52466.0  13887.0           775             5        Salaried
 1      2   57  74188.0    500.0           598             2   Self-Employed
 2      3   51  57827.0  30807.0           531            10   Self-Employed
 3      4   41  52145.0  14022.0           688             9        Salaried
 4      5   41  36358.0  31375.0           754             9   Self-Employed
 ..   ...  ...      ...      ...           ...           ...             ...
 292  293   65  62702.0  27333.0           719             7   Self-Employed
 293  294   36  51594.0  27684.0           638             9   Self-Employed
 294  295   46  60916.0    500.0           680             1        Salaried
 295  296   45  61515.0    500.0           759             4        Salaried
 296  297   60  78772.0  30021.0           635             1      Unemployed

     risk_grade region  credit_limit  used_credit  revenue   profit   ebitda  \
 0            A  South      214544.0      30744.0  73659.0  15290.0  32354.0
 1            A   East      130761.0      19542.0  88734.0  12895.0  19499.0
 2            A  North      234444.0      53255.0  48647.0   3954.0   8629.0
 3            B   West      233162.0      17957.0  46928.0   8187.0  17720.0
 4            D   West      114660.0      41472.0  52901.0   4611.0   6191.0
 ..         ...    ...           ...          ...      ...      ...      ...
 292          A  South      293714.0      40724.0  91599.0   7982.0  15101.0
 293          B  South      220712.0      46208.0  63547.0   6726.0  11833.0
 294          C   East      103893.0      16936.0  94285.0  14098.0  16932.0
 295          A   East      184659.0      21152.0  77380.0   5499.0   6792.0
 296          C   East      310686.0      42533.0  95663.0   6416.0  14057.0

      interest_expense  debt_ratio
 0              2107.0    0.264686
 1               100.0    0.006740
 2              5154.0    0.532744
 3               738.0    0.268904
 4              4798.0    0.862946
 ..                ...         ...
 292            4481.0    0.435919
 293            2498.0    0.536574
 294             100.0    0.008208
 295             100.0    0.008128
 296            3497.0    0.381113

 [297 rows x 16 columns],
 0      0
 1      0
 2      0
 3      0
 4      1
       ..
 292    0
 293    0
 294    0
 295    0
 296    1
 Name: default, Length: 297, dtype: int64)